server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: "SAA01-HelloWorld"
  ai:
    dashscope:
      api-key: ${SpringAIAlibabaStudyApiKey}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: deepseek-v4-flash
