server:
  port: 8088
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  profiles:
    active: dev
  application:
    name: "SAA04-StreamingOutput"
  ai:
    dashscope:
      api-key: ${SpringAIAlibabaStudyApiKey}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: deepseek-v4-flash

